### ISSUE TITLE
Implement Missing Locales for Number/Date Formatting within Specifications

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#11]
As Vega uses the d3 formatters, we've implemented the locales in d3 that cross-over with the Power BI locales for the beta, but there are a number of gaps commented in `src/config/locales.ts`. We need to complete these as much as we can to ensure that we can support all Power BI locales.

**Comment by smashmirrorcardboardface** [comment]
how do I currently implement the en-gb locale?

**Comment by dm-p** [comment]
Deneb reads your locale according to what Power BI provides, so if you're using the [custom formatter](https://deneb-viz.github.io/formatting-values#power-bi-custom-formatter) then this should pass through the locale and format it accordingly (as this custom formatter uses the MS-provided libraries). If this isn't working for you, please open a separate issue with details and I can track separately, and possibly check with MS if necessary.

If you're using the standard formatter (D3 syntax) then en-GB appears to have been missed out of my list so I'll need to add support for it. I'll track this separately and include in 0.5 (due out in a couple of weeks).

If you want to manually specify the locale, then this is a new feature request. Similarly, please create a new issue with your requirements and I'll see what I can do.

**Comment by smashmirrorcardboardface** [comment]
great, the d3 syntax is all I'd need.  For now i can use the PB formating option and throw a gbp pound sign in front.
