### ISSUE TITLE
Cross Highlighting Support

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#170]
Fantastic visual. 

It seems Deneb can cross filter _and_ cross highlight other visuals (where other visuals support cross highlighting like the bar chart below).

![image](https://user-images.githubusercontent.com/86846675/145619292-822fa351-516e-481f-9ada-6f622771fb98.png)

However, the inverse seems to be that other visuals can _only_ cross filter Deneb but not cross highlight as per the image below when clicking on France in the table. 

![image](https://user-images.githubusercontent.com/86846675/145619491-21e485d6-1aba-45a1-a651-41007189a08c.png)

Is this correct? Is it possible to cross highlight Deneb charts instead of cross filtering them?

**Comment by dm-p** [comment]
Thanks for taking the time to provide feedback! I appreciate it :)

Cross-highlighting is quite complicated to handle generically in a visual and will require more thought (and will more investment from you as a creator to manage how your design should work visually). This has already been raised in #134 with current thoughts documented so I'd suggest continuing any discussions in there.
