### ISSUE TITLE
10000 values limit

### ISSUE THREAD

**Issue by StepAll** [deneb-viz/deneb#186]
Hi, guys!
First of all, thanks a lot for a great job! Love the product: Deneb-viz looks very impressive!
Not an issue just question.

Working with vega-lite and 80000+rows-dataset I've run into data limitation in 10000 values.
Is it done intentionally?
I haven't found any information about it in the documentation.
What does 80000+dots-scatterplot look in PBI on the picture (left one with ggplot in R)
![image](https://user-images.githubusercontent.com/97505829/149077246-bb80820c-5d87-4653-baa9-16a3e0505b3b.png)

I'd like to switch all my R-viz to Deneb-viz. How is it possible to overcome 10000 values limitation?

**Comment by dm-p** [comment]
Hi, and thanks!

Not sure if you've seen it in the documentation but it is possible to [break the 10K standard limit](https://deneb-viz.github.io/dataset#data-row-limits) but note that the amount of rows provided to the visual is dependent on Power BI resources and the action of fetching additional windows of 10K rows can depend on the  performance of the underlying DAX query.

Also note the performance considerations in the documentation - your visual may perform better rendering as Canvas over SVG.

**Comment by StepAll** [comment]
ohh, thanks so much! It worked out!
btw, I used this link for documentation https://deneb-viz.github.io/
