### ISSUE TITLE
Error Message "should NOT have additional property: hconcat"

### ISSUE THREAD

**Issue by pawarbi** [deneb-viz/deneb#192]
Hi Daniel - 
I wrote a[ blog o](https://pawarbi.github.io/blog/power%20bi/deneb/custom%20visual/altair/python/2022/01/22/Deneb-Custom-visual-interactive-widget-composite.html)n using Deneb in Power BI. I am able to create the visual (see code below), however, I see errors with yellow triangles "should NOT have additional property: hconcat". Any idea what is this error and how can I fix it? The visual works as expected, just not sure what the error is for. Thanks

`{
  "config": {
    "view": {
      "continuousWidth": 400,
      "continuousHeight": 300
    }
  },
  "hconcat": [
    {
      "layer": [
        {
          "mark": "bar",
          "encoding": {
            "color": {
              "condition": {
                "value": "#477998",
                "test": "(datum.Z < SelectorName.color_threshold)"
              },
              "value": "hsla(232, 7%, 20%, 0.25)"
            },
            "tooltip": [
              {
                "type": "quantitative",
                "field": "X"
              },
              {
                "type": "quantitative",
                "field": "Y"
              },
              {
                "type": "quantitative",
                "field": "Z"
              }
            ],
            "x": {
              "type": "quantitative",
              "field": "X"
            },
            "y": {
              "type": "quantitative",
              "field": "Z"
            }
          },
          "height": 400,
          "selection": {
            "selector017": {
              "type": "interval",
              "bind": "scales",
              "encodings": ["x", "y"]
            },
            "SelectorName": {
              "type": "single",
              "fields": [
                "color_threshold"
              ],
              "bind": {
                "input": "range",
                "max": 100,
                "min": 0,
                "name": "color_threshold:",
                "step": 1
              },
              "init": {
                "color_threshold": 20
              }
            }
          },
          "title": "Bar Chart with Widget",
          "width": 500
        },
        {
          "mark": {
            "type": "text",
            "align": "right",
            "baseline": "middle",
            "dx": 3,
            "dy": -5
          },
          "encoding": {
            "color": {
              "condition": {
                "value": "#477998",
                "test": "(datum.Z < SelectorName.color_threshold)"
              },
              "value": "hsla(232, 7%, 20%, 0)"
            },
            "text": {
              "type": "quantitative",
              "field": "Z"
            },
            "tooltip": [
              {
                "type": "quantitative",
                "field": "X"
              },
              {
                "type": "quantitative",
                "field": "Y"
              },
              {
                "type": "quantitative",
                "field": "Z"
              }
            ],
            "x": {
              "type": "quantitative",
              "field": "X"
            },
            "y": {
              "type": "quantitative",
              "field": "Z"
            }
          },
          "height": 400,
          "title": "Bar Chart with Widget",
          "width": 500
        }
      ]
    },
    {
      "mark": "circle",
      "encoding": {
        "color": {
          "condition": {
            "value": "red",
            "test": "(datum.Z < SelectorName.color_threshold)"
          },
          "value": "hsla(232, 7%, 20%, 0.25)"
        },
        "tooltip": [
          {
            "type": "quantitative",
            "field": "X"
          },
          {
            "type": "quantitative",
            "field": "Y"
          },
          {
            "type": "quantitative",
            "field": "Z"
          }
        ],
        "x": {
          "type": "quantitative",
          "field": "X"
        },
        "y": {
          "type": "quantitative",
          "field": "Y"
        }
      },
      "height": 400,
      "selection": {
        "SelectorName": {
          "type": "single",
          "fields": ["color_threshold"],
          "bind": {
            "input": "range",
            "max": 100,
            "min": 0,
            "name": "color_threshold:",
            "step": 1
          },
          "init": {
            "color_threshold": 20
          }
        }
      },
      "title": "Scatterplot with Widget",
      "width": 300
    }
  ],
  "data": {"name": "dataset"}
}`

![image](https://user-images.githubusercontent.com/62612119/150862340-653e6631-b363-4b7e-88fe-a101b3052889.png)

**Comment by pawarbi** [comment]
Thanks @dm-p , that answers my question. Thanks for everything!

**Comment by dm-p** [comment]
Thanks for your support!
