### ISSUE TITLE
Edit Placeholder Fields

### ISSUE THREAD

**Issue by rhershfield** [deneb-viz/deneb#195]
1.	Select Create New Specification
2.	Select Line Chart with Interval Band
3.	Assign columns to the placeholders
4.	Click Create
5.	How can I go back and change which columns are assigned to the placeholders? I made a mistake and want to correct it without starting over, if possible.

**Comment by dm-p** [comment]
In the current version, you can manually modify your specification accordingly. If you haven't made any changes to the template, you can also click the **New Specification** button, re-select the desired template and re-bind your fields.

In 1.1 (currently undergoing deployment from MS), you will be able to re-map fields from the [Edit Specification Field Mapping](https://deneb-viz.github.io/next/changelog#specification-field-mapping-160) dialog (#160). The ETA for this is 'soon'.

**Comment by dm-p** [comment]
Closing, based on [response here](http://disq.us/p/2mioncs).
