### ISSUE TITLE
Add access to individual Theme Colours

### ISSUE THREAD

**Issue by Greg-Philps** [deneb-viz/deneb#197]
Explore (and add, if easily possible) the ability to directly reference a specific member of the PBIX file colour theme, say something like

```
"color": { "expr": "pbiThemeColor(1)" }
```

instead of using a colour name or HEX code to represent the first theme colour?

**Comment by dm-p** [comment]
Thanks for the feature request @Greg-Philps!

I'll have a think about some more of the specifics, but would a zero-based index for the palette be acceptable if wishing to select by number? This is more consistent with how Power BI allocates the theme colour palette internally, and also consistent with JavaScript and Vega expressions, which all use zero-based indices.

I might also propose that we add an expression that can specify a name or key, which is [also how the Power BI API 'reserves' colours by category](https://github.com/microsoft/powerbi-visuals-api/blob/c5e45704e986ab4bc98a7aadc0a8539683d66d54/index.d.ts#L1309). This way, we could supply a named string value, which means that we could re-use the name elsewhere in the spec and the correct colour could be looked up without assigning a new one.

**Comment by Greg-Philps** [comment]
Whatever is easiest ... as Deneb/Vega-Lite is full-code, one would be typing regardless. My first thought was to mimic the numbering assignments in the PBIX theme dialog, but zero-based numbering works great. Name or Key sounds great, more options and, as you said, allows/encourages reuse.

**Comment by Greg-Philps** [comment]
Just had another thought: if the individual theme colours are accessible, can the associated opacities be accessible as well? (e.g., not only the theme 1 colour, but also the 60% lighter, 40% lighter, 20% lighter, 25% darker, and 50% darker colours as per the colours presented in the Power BI colour palette)

**Comment by dm-p** [comment]
Hi @Greg-Philps, and here's how I'm thinking this should work in 1.3. Would really appreciate you thoughts:

* We'll expose a custom function, called `pbiColor(index, shadePercent)`
* `index` is a zero-based number that specifies which colour from the palette to extract
* `shadePercent` is an optional modifier that will shade the colour by the supplied percentage
    * Valid values are decimals from -1 to 1.
    * If negative, the colour will be darkened by that amount
    * If positive, the colour will be lightened by that amount
    * If zero, the colour will be the same as the colour palette (i.e. unmodified)

I couldn't get any traction from MS on getting API changes made, and from black-box testing the results, the method MS uses to created the shades in the palette doesn't seem to be a simple brightness adjustment. I've unit tested the results of my method against a couple of Power BI themes and I think that we have is a good match :)

Here's a short video of it working, which should help get this across also:

https://user-images.githubusercontent.com/10572054/167340568-ea9bc59c-dcb1-4f22-8517-19ed56a32ec2.mp4

**Comment by Greg-Philps** [comment]
Hi @dm-p. Looks awesome. You're description was right on the money, and I knew exactly what to expect when I saw your demo video. This is even more flexible that the values Power BI provides in its colour-picker dialog (60% lighter, 40% lighter, 20% lighter, 25% darker, and 50% darker). Can't wait. Thanks for all your efforts. Greg

**Comment by dm-p** [comment]
Initial functionality introduced in 1.3's first alpha build. If there are any further issues, please create a new issue with the prefix `[1.3 Alpha Testing]` and I'll flag for follow-up.
