### ISSUE TITLE
Investigate CodeMirror v6

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#229]
Ace is functional but somewhat of a hinderance with trying to make productivity improvements in the editing portion of the UI.

I've tried getting Monaco to work countless times but it's unlikely that we'll ever get it to work, given that we would need to host the workers somewhere external, and this is a no-go for certification.

CodeMirror v6 may be a much better candidate for an embedded editor, so we'll need to take look at this and see if we can do a bit more with it that we can currently with Ace.

**Comment by dm-p** [comment]
CodeMirror v6 definitely doesn't use web workers, which is a great way towards finding a better candidate. However, I'm having trouble with webpack loading lezer/JSON language support and I've created microsoft/powerbi-visuals-tools#423 to assist with making this possible in the OoB tooling.

There's no JSON schema support in CodeMirror, or any third party tools, but I'm having some success with [vscode-json-languageservice](https://github.com/microsoft/vscode-json-languageservice). Because this is designed for use with Monaco, it's not 100% perfect and needs some intervening logic to bridge with CM, but it solves a lot of our cases around autocompletion from the JSON schema.

**Comment by dm-p** [comment]
MS are not really coming to the party with the PR, so I'll continue to work with Ace Editor for v2.

**Comment by zBritva** [comment]
Web workers can be bundled into the visual package and loaded as blobs
There is sample Power BI Visual project with typescript editor:
https://github.com/zBritva/powerbi-visuals-monaco-editor

But the visual package becomes huge.
