### ISSUE TITLE
Review/Improve Visual Editor Heading when Expanded

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#230]
The "Visual Editor" heading text in the editor pane feels a little redundant now, and whilst it's only around 25px high, it's some space we can potentially re-claim.

Current thoughts:

- Remove heading when expanded; keep it when collapsed
- Move the 'collapse' button onto the command bar, next to the help (?) icon

**Comment by PBI-David** [comment]
Agreed. More space back would be useful.

**Comment by dm-p** [comment]
The top of the Editor Pane will look as follows when 1.4 alpha builds start-up:

![image](https://user-images.githubusercontent.com/10572054/169177245-8d45336a-900e-4375-a0ed-fd9300994b54.png)
