### ISSUE TITLE
[1.3 Alpha Testing] "Cannot read properties of undefined (reading '0')" Error

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#233]
I have an interactive line chart that I use for testing, and this throws a `Cannot read properties of undefined (reading '0')` for the following scenarios:

- Initialisation (very rarely)
- Editor pane position change (every second time)
- Applying config changes (every second time)

I suspect there's a race condition of some kind, but needs some detailed analysis to determine if it's my fault as an author, or Deneb's (probably Deneb's).

**Comment by hcoohb** [comment]
This happens to me very randomly as well,
Especially on deneb in PBI services.
It tends to happen more often on a page where there are several deneb graphs.

**Comment by dm-p** [comment]
Thanks for the feedback - it's not happened for me since raising (hence moving to the backlog). It would be good to know if there's anything specific in your designs (such as reliance on params or signals) that might help me isolate what's going on with it? I'd love to try and get it fixed if I can (but its been hard for me to trap).

**Comment by dm-p** [comment]
We've been finding that a lot of issues stem from react-vega not making the dataset available at parse time (see related issues), and this can sometimes cause issues with some areas of Vega/Vega-Lite when working things out. As of 1.6, we'll be patching the dataset into the spec before we parse and render, which appears to mitigate many of these issues.
