### ISSUE TITLE
Scroll Bars

### ISSUE THREAD

**Issue by canine-afficionado** [deneb-viz/deneb#249]
This tool is fantastic thanks.

Is there any way it can automatically show scroll bars like Power BI does with a wide column chart for example? It allows scrolling whilst preserving the y axis labels.

I've seen the Vega workarounds using a parameter slider or hconcat but I would love it to be consistent with the other visuals in Power BI.

Thanks.

**Comment by dm-p** [comment]
Hi there, and thanks very much for your feedback :)

What you're after is not a Vega feature, and will not be possible to do from within Deneb - the workarounds you have already listed are the currently established ways of being able to manage it.

If this is something that you'd like in Vega or Vega-Lite, then I would suggest making a feature request in the appropriate repository for the team to have a look at. It certainly sounds sensible, but I know from experience in developing a dedicated custom visual that it might be a fair amount of effort to get it to work in a more flexible scenario like this, and it's unlikely that the team would be able to extend this to supporting the canvas renderer if they could achieve it.
