### ISSUE TITLE
Vega-lite Parameter checkbox not clickable when Cross-Filtering enabled

### ISSUE THREAD

**Issue by hcoohb** [deneb-viz/deneb#254]
When creating a Checkbox parameter with vega-lite, if the Cross-Filtering is enabled, clicking the checkbox does not toggle it.
It works fine is Cross-Filtering is disabled.

Using deneb 1.3.0.0 from Microsoft AppSource

The following spec can be used to test:
https://vega.github.io/editor/#/gist/1e5d2598265f3556adee09260adbf94a/spec.json

**Comment by dm-p** [comment]
Thanks for letting me know. I don't have capacity to investigate in-detail at present, but suspicion is that the clear catcher element (used to auto-clear interactivity events if whitespace is clicked) extends over the `form` element the Vega view creates for these elements (or its propagating the events incorrectly). I'm not planning any new features until v2, but will see if I can get this into a patch release once I have some time to sit down and work through the issue in detail.

**Comment by dm-p** [comment]
May possibly have something to do with #246 also (which is why the clear-catcher sprung to mind; thought I'd resolved that...). TBC when I can investigate further.

**Comment by hcoohb** [comment]
Thanks for the quick reply!

I also forgot to add that it seems to only impact the checkbox "toogling".
Parameters such as sliders and selectbox work as expected (select is much slower on deneb than on vega-lite online builder, but still works)

**Comment by dm-p** [comment]
I've reworked the bugfix changes in #246 so they work more simply:

https://user-images.githubusercontent.com/10572054/181139108-6d53ccf1-0edd-4915-8a64-dddd0952972c.mp4

Note that param bindings are refreshed whenever Power BI sends an update the the visual (and re-initialising the Vega view). We may be able to improve this and it's still on the backlog for later on, as per the notes in #246 also.

It is a lengthy process to submit and re-certify visuals in AppSource, so I'd like to be sure that we have this right, based on current functionality. I'd appreciate if you're able to have a look at the [latest alpha channel build](https://github.com/deneb-viz/deneb/releases/tag/alpha) and confirm this works as you expect. If you need more details on working with the early access builds, you can [read more on the documentation site about this](https://deneb-viz.github.io/community/early-access).

**Comment by hcoohb** [comment]
@dm-p wow, that was fast!

Yes, just tested the latest alpha and it works like a charm with my own data and a quite complex report with cross-filtering.
Thanks a lot!

**Comment by dm-p** [comment]
Glad to hear it's working! This will be fully resolved once 1.4 is deployed through AppSource (I'll be submitting soon once we're through alpha/beta testing).
