### ISSUE TITLE
Copy Icon in PowerBI Service

### ISSUE THREAD

**Issue by rhershfield** [deneb-viz/deneb#256]
The new Copy icon available in Power BI Service is supposed to copy a visual as an image to the clipboard. When I try using this feature it works for standard Power BI visuals but not for Deneb visuals. Is this capability supported in the current v1.3.0.0 release or planned for a future release?

**Comment by rhershfield** [comment]
Daniel, Thanks for the quick and detailed explanation. FYI, I tried using Canvas instead of SVG thinking that might offer a solution but it also failed.

Deneb has elevated Power BI from an interesting but useless toy to a robust solution for our charting needs. The build-in charting visuals are pathetic in terms of their lack of control over chart properties. Without Deneb we'd still be using Excel. So thanks for all your hard work!

**Comment by dm-p** [comment]
Just a quick note to say that I haven't forgotten about this one. For v2 development, I'm completely re-architecting and re-writing the visual, and one thing I'm doing as part of this is binding the Vega rendering events more tightly to the Power BI visual rendering events. 

I don't have an ETA yet, and again, it'll be difficult to verify until that release fully goes through AppSource approval and deployment, but it's definitely being taken into consideration in my current work.

**Comment by rhershfield** [comment]
That's great news and I appreciate the follow-up. We have an upcoming project where a requirement is for users to be able to copy/paste charts. Screen capture is a viable workaround but not as precise.

**Comment by dm-p** [comment]
I have tested this for many visuals in Deneb 1.6 now that it is live in AppSource, and this is working successfully for me, e.g.:

![image](https://github.com/deneb-viz/deneb/assets/10572054/54cde043-babe-4551-8f0a-1b5017a61409)

Suppose there are any visuals you have that still do not work. In that case, it is recommended that you open a new issue with a reproducible example so we can look into them specifically. 

I hope that these recent changes solve your issue.
