### ISSUE TITLE
Excel Add-in like for PBI

### ISSUE THREAD

**Issue by mujkice** [deneb-viz/deneb#263]
I love Deneb. Its the best custom visual for PBI I know. 
I do a lot of stuff also on Excel. 
Do you think it would be a big task to make also similar Addin for Excel. 
I believe they joined 2 stories together and also combined it with PowerPoint. It would be great if I had possibility to use this knowledge also on building visuals in Excel. 
Keep up the good work:-)

**Comment by dm-p** [comment]
Hi there, and glad to know you like Deneb :)

I'm sure that producing an Excel add-in would be a significant undertaking. There are significant differences in Power BI and Excel in how their visual layer works, and also the technologies used to develop for them. This is not something I have the time or resources to explore, I'm afraid.
