### ISSUE TITLE
Aggregate Text Formatting issue

### ISSUE THREAD

**Issue by alxdean** [deneb-viz/deneb#265]
When using the joinaggregate function to sum up values within the visual the text representations are forced into a bold state. This seems to be done by the visual itself and I can't find a way to overcome this bold effect. It would not be an issue if the rendering of the text were not so choppy. 

![image](https://user-images.githubusercontent.com/7785921/199462137-c540d3e3-466b-49e0-8704-2b94543edf2e.png)
![image](https://user-images.githubusercontent.com/7785921/199462234-766020f9-e5ec-4288-8fd2-621e15aa5742.png)

only happens with the joinaggregate component of the visual. 
Even setting the font-weight to 100 is being ignored. 

here the full vega
```
{
  "data": {"name": "dataset"},
  "vconcat": [
    {
      "width": 100,
      "layer": [
        {
          "mark": {
            "type": "rect",
            "width": 100
          }
        },
        {
          "mark": {
            "type": "text",
            "color": "black",
            "align": "right",
            "dx": 30,
            "fontSize": 13
          },
          "encoding": {
            "x": {
              "field": "key",
              "type": "nominal",
              "axis": {
                "labelAngle": 0,
                "orient": "top"
              },
              "title": null,
              "scale": {"padding": 0.05}
            },
            "y": {
              "field": "KONTO",
              "type": "ordinal",
              "title": "Kunde",
              "sort": {"field": "I"}
            },
            "text": {
              "field": "value",
              "format": ".2f"
            }
          },
          "transform": [
            {
              "filter": {
                "field": "Beschreibung",
                "gte": "Top"
              }
            },
            {"fold": ["Umsatz", "DB"]}
          ]
        }
      ]
    },
    {
      "width": 100,
      "layer": [
        {
          "mark": {
            "type": "rect",
            "width": 100
          }
        },
        {
          "mark": {
            "type": "text",
            "color": "black",
            "align": "right",
            "dx": 30,
            "fontSize": 11,
            "font": "Verdana",
            "fontWeight": 100
          },
          "encoding": {
            "x": {
              "field": "key",
              "type": "nominal",
              "axis": null,
              "title": null,
              "scale": {"padding": 0.05}
            },
            "y": {
              "field": "Beschreibung",
              "type": "ordinal",
              "title": null,
              "sort": {"field": "I"}
            },
            "text": {
              "field": "value",
              "format": ".2f"
            }
          },
          "transform": [
            {
              "joinaggregate": [
                {
                  "op": "sum",
                  "field": "Umsatz",
                  "as": "aggUmsatz"
                }
              ],
              "groupby": [
                "Beschreibung"
              ]
            },
            {
              "joinaggregate": [
                {
                  "op": "sum",
                  "field": "DB",
                  "as": "aggDB"
                }
              ],
              "groupby": [
                "Beschreibung"
              ]
            },
            {
              "fold": [
                "aggUmsatz",
                "aggDB"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by PBI-David** [comment]
I don't think this isn't bold text. I think it is multiple text marks being laid over one another because you're using joinaggregate.

**Comment by dm-p** [comment]
Thanks very much for your report. This is a feature of the languages, however and not an issue with the visual.

`joinaggregate` is usually used when you want to keep the cardinality of the dataset without aggregating it. By preserving the cardinality, multiple marks with the same encoding values will overlay, causing this effect.

For this case, `aggregate` transforms are probably more appropriate.

If you need assistance with how to proceed, I'd recommend [asking in one of the communities](https://deneb-viz.github.io/support#getting-support) that focus on supporting the languages, as there will be many more people who can help you in a more timely manner than I can. I maintain the visual for free, in my free time, so I do not have the capacity to provide specific support for the Vega and Vega-Lite languages.

**Comment by alxdean** [comment]
Ok. Now the choppy look makes more sense. Overlay. I tried using aggregate but it gave me back 0 or nan. I'll try to find my Problem with aggregate and use that instead. 
The tricky part is that I have only one dataset and want to show individuals in the top 10 and summaries in the bottom one. That's why I'm doing the transform in each vconcat and not once at the data layer.
