### ISSUE TITLE
Deneb and Performance Analyzer

### ISSUE THREAD

**Issue by avatorl** [deneb-viz/deneb#267]
I see ([screen capture](https://dl.dropboxusercontent.com/s/jmzvto5kq2lwpem/PBIDesktop_AnrBmiy09q.gif)) that Performance Analyzer already displays time, but Deneb is still rendering the chart. Does it mean Performance Analyzer doesn't detect time required to render the chart (and only detects time to load Deneb?)? Is it possible to make it working correctly and display total time required to load Deneb and render Vega visualization inside?

**Comment by dm-p** [comment]
This is an interesting question - thanks for raising it. With custom visuals, we only have access to a [rendering events API](https://learn.microsoft.com/en-us/power-bi/developer/visuals/event-service), which signals to listeners within the main window. This is typically used for export to PDF and PowerPoint, so the processes assembling the output know when a visual is has started and finished rendering.

Deneb has the `renderingFinished()` event [synced to the Vega view already](https://github.com/deneb-viz/deneb/blob/4a5e83368cab5240c8f36e63d7bbad99c3539286/src/core/vega/index.ts#L164). We've identified an existing issue (#256) where this is perhaps not quite as good as it can be. I am re-writing the visual workflow in v2 to better handle these scenarios.

However, I have done some testing with a long-running visual I have using the current v2 codebase and while the signal is now emitted at the correct time when a visual is first run (when the Vega view completes the render), the Performance Analyzer ignores this and seems to be related to something that the main window is emitting that we don't have control over. So, basically, the changes I'm planning don't affect this for the better :(

I will need to follow this up with MS to see if (a) the Performance Analyzer is in-scope for rendering events and I'm possibly doing something wrong, and (b) if this is not in-scope, whether they can possibly address it.

For now, I'll label this as a Power BI/visuals SDK limitation until I can get more information.

**Comment by dm-p** [comment]
Just to keep this up to date, I raised this as an enhancement with the custom visuals folks a little way back, so I'll continue to monitor and see if we ever hear anything back on it.

**Comment by dm-p** [comment]
Hey @avatorl: I don't have your sample workbook to check against, but I think that the changes made to rendering events in 1.6 may have fixed this, but they will only be correct for the AppSource version. We can't hook into these events for the standalone visuals, but if you're using the AppSource version, I'd like to know if this looks better for you.

The examples I've tried with long render times all seem to be in line with what I expect, so it would be good to see if we can close off (and I can write up the details about performance analyzer integration on the doc site if the results are similar for you).

**Comment by dm-p** [comment]
Per the previous comment, I'm pretty sure this has been solved through work on other issues. If not, please reopen with some examples we can use to validate.
