### ISSUE TITLE
Feature Request: Spec Export With Data Option

### ISSUE THREAD

**Issue by Giammaria** [deneb-viz/deneb#277]
Hey Daniel. Here with another idea that could make receiving help in the community, as well as taking development in-and-out of deneb easier. We have the ability to export templates, which is a very nice feature. Having an option to export a vega/vega-lite spec with the dataset values included in the values array portion of the data object would also be nice. Of course this has the potential to really bloat a spec, but I could see it being an option. Maybe even have a warning that is visible saying that the data should be sanitized before sharing the spec with others. I've run into many instances on the Power BI Community forums where I have wanted to help someone, and they were willing to share their data, but the process of doing some was a bit cumbersome. I'm sure you can relate.

**Comment by dm-p** [comment]
Hi Madison, and thanks for raising. This has already been raised as #202, so I'll close this one down to avoid duplication and I suggest that anything further gets added to the original one.
