### ISSUE TITLE
Add HTML/SVG defs for Pattern Fill

### ISSUE THREAD

**Issue by kolky001** [deneb-viz/deneb#30]
Ability to easily add pattern fill to marks via html/svg defs

**Comment by dm-p** [comment]
For context, [this is the article that was referenced when discussing the requirement elsewhere initially](https://observablehq.com/@oliviafvane/how-to-use-textures-patterns-in-vega-lite). We may be able to make the process easier within the visual for folks that might want this, but...

...we may want to keep an eye on vega/vega#1372 also, which is tracking the feature for Vega and would ideally add canvas support in addition to SVG.

**Comment by dm-p** [comment]
Feature complete in build 115.
