### ISSUE TITLE
[Error] invalid size

### ISSUE THREAD

**Issue by avatorl** [deneb-viz/deneb#300]
I have a Deneb/Vega visualization. The code is long - 95K rows (embedded geojson) and it uses "kde2d" and "isocontour" data transformations (not sure if related, but this is what makes this visualization different from the other ones in the same report).

In the editor have to click Apply button twice to render this visualization. First time it returns [Error] invalid size error. Then I have to make any change in the code (e.g. inserting or removing a blank row) to make Apply button active and click it again. No errors.

Then, after any code change (including inserting or removing a blank row) - the same problem. First code change leads to the error. Second code change - fixes the problem. And again, again, again the same behavior.

(I can send you the file)

**Comment by dm-p** [comment]
Can you reproduce in the 1.5.1 alpha or beta builds?

**Comment by avatorl** [comment]
I'll try with alpha/beta builds.

And I've just checked what part of code creates the problem and it seems to be "kde2d" transformation. When I remove it, everything else works well. Probably the error message is related to "size" property of "kde2d" transformation.

**Comment by dm-p** [comment]
Good to hear! That version is currently undergoing certification, so should be generally available soon.

Are we good to close this one off?

**Comment by dm-p** [comment]
I assume that no news is good news, so I'm closing this one. Feel free to re-open if you're still able to reproduce on 1.5.1 (although I'll need some supporting materials to help me to debug it).
