### ISSUE TITLE
Daniel out of Office: 8 May - 5 Jun 2023

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#301]
I'm finally getting around to taking my trip back to the UK that I was originally scheduled to take in 2020. During this time, I won't be actively working on Deneb development or support, as I haven't taken a proper break for quite some time (and I haven't seen my family in over 12 years). I may check in from time to time but will look at any new issues properly when I return.

I will however be speaking at two Power BI user groups while I'm away, if you're keen to come along and find out more (or to say hi):

- [Thurs 18th May: Birmingham User Group](https://www.meetup.com/birmingham-power-bi-meet-up-group/events/292993427/)
- [Thurs 25th May: Manchester User Group](https://www.meetup.com/pbimcr/events/vsvtrsyfchbhc/)

**Comment by Giammaria** [comment]
Enjoy your trip! Well deserved! Thanks for all that you do.- MadisonSent from my iPhoneOn May 1, 2023, at 6:55 PM, Daniel Marsh-Patrick ***@***.***> wrote:﻿
I'm finally getting around to taking my trip back to the UK that I was originally scheduled to take in 2020. During this time, I won't be actively working on Deneb development or support, as I haven't taken a proper break for quite some time (and I haven't seen my family in over 12 years). I may check in from time to time but will look at any new issues properly when I return.
I will however be speaking at two Power BI user groups while I'm away, if you're keen to come along and find out more (or to say hi):

Thurs 18th May: Birmingham User Group
Thurs 25th May: Manchester User Group
