### ISSUE TITLE
Horizontal scroll bar always present even when chart should fit when using "fit-y" in Vega spec

### ISSUE THREAD

**Issue by DaveTN** [deneb-viz/deneb#315]
I hope I am posting this issue in the correct location. This is my first time ever posting an issue to a GitHub project. I have been using Deneb for a little while in several Power BI reports but have recently switched to Vega instead of Vega-Lite because I find in much more intuitive when dealing with multiple Y axes in my charts.

I have been trying to create a simple column chart (only one Y-axis) which may at times display 30-50 columns and at other times 1-5 columns depending on filters applied by the report user using slicers on the report page. I have been trying to make the chart behave similarly to the native column chart visual in Power BI in that, when showing only a few columns, the width of each column adjusts to fill the space available, but when the number of columns exceeds an amount that can fit while still maintaining a minimum width of 20, they width will stay at 20 and the user will have to scroll horizontally to see all the columns. 

In order to accomplish this, I am using a signal to calculate the number of visible columns, determine the appropriate step size for the width of the "rect" mark, and then setting the step size using that signal. The other element that goes into making this work is to set the "type" property of the "autosize" object to "fit-y" to allow for horizontal scrolling as needed. The problem I am having is that whenever I use "fit-y" there is a horizontal scroll bar present ALWAYS--not just when the columns exceed the available space. This appears to be happening because anytime "fit-y" is used, the right edge of the area occupied by the columns is pushed just beyond the edge of the viewable area. This beccomes obvious when I use grid lines and view the chart in the edit window (see screenshots below). The chart shown in the second screenshot always contains a horizontal scroll bar regardless of how few columns are visible.

Is there a solution to this issue by adjusting anything in my Vega spec? Or is this an issue with the Deneb visual that would have to be fixed at that level? Thanks in advance for any help!

![fit](https://github.com/deneb-viz/deneb/assets/135339397/c9adad21-52e0-4ab8-b09b-b33c23c20a96)
![fit-y](https://github.com/deneb-viz/deneb/assets/135339397/46c15420-5e62-4cbc-9e85-f8981f5ef972)

Here is the Vega specification code. The second code block below is the config code. **The only difference between the two versions show in the screenshots is the "type" value of the "autosize" object in the config code ("fit" vs "fit-y").**

`{
  "data": [
    {
      "name": "dataset"
    }
  ],
  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {
        "data": "dataset",
        "field": "Letters"
      },
      "range": {"step": 20},
      "paddingInner": 0.1,
      "paddingOuter": 0.5,
      "round": true
    },
    {
      "name": "yscale",
      "domain": {
        "data": "dataset",
        "field": "Numbers"
      },
      "nice": true,
      "range": "height"
    }
  ],
  "axes": [
    {
      "orient": "bottom",
      "scale": "xscale"
    },
    {
      "orient": "left",
      "scale": "yscale",
      "tickCount": 5,
      "grid": true,
      "gridColor": "#000000",
      "gridDash": [1, 3],
      "labelOverlap": "parity",
      "labelFlush": false
    }
  ],
  "marks": [
    {
      "name": "bars",
      "type": "rect",
      "style": "MyBar",
      "from": {"data": "dataset"},
      "encode": {
        "enter": {
          "x": {
            "scale": "xscale",
            "field": "Letters"
          },
          "width": {
            "scale": "xscale",
            "band": 1
          },
          "y": {
            "scale": "yscale",
            "field": "Numbers"
          },
          "y2": {
            "scale": "yscale",
            "value": 0
          },
          "tooltip": {
            "signal": "datum.Numbers"
          }
        }
      }
    },
    {
      "type": "text",
      "from": {"data": "dataset"},
      "style": "DataLabel",
      "encode": {
        "enter": {
          "align": {"value": "center"},
          "x": {
            "scale": "xscale",
            "field": "Letters",
            "band": 0.5
          },
          "y": {
            "scale": "yscale",
            "field": "Numbers"
          },
          "text": {"field": "Numbers"}
        }
      }
    }
  ]
}`

`{
  "autosize": {
    "contains": "padding",
    "type": "fit-y"
  },
  "view": {"stroke": "transparent"},
  "font": "Segoe UI",
  "arc": {},
  "area": {
    "line": true,
    "opacity": 0.6
  },
  "bar": {},
  "line": {
    "strokeWidth": 3,
    "strokeCap": "round",
    "strokeJoin": "round"
  },
  "path": {},
  "point": {"filled": true, "size": 75},
  "rect": {},
  "shape": {},
  "symbol": {
    "strokeWidth": 1.5,
    "size": 50
  },
  "text": {
    "font": "Segoe UI",
    "fontSize": 12,
    "fill": "#605E5C"
  },
  "axis": {
    "labelFontSize": 10,
    "ticks": false,
    "grid": false,
    "domain": false,
    "labelColor": "#605E5C"
  },
  "axisQuantitative": {
    "tickCount": 3,
    "grid": true,
    "gridColor": "#000000",
    "gridDash": [1, 5],
    "labelFlush": false
  },
  "axisX": {"labelPadding": 5},
  "axisY": {"labelPadding": 0},
  "style": {
    "MyBar": {
      "cornerRadiusTopLeft": 2,
      "cornerRadiusTopRight": 2,
      "fill": "green"
    },
    "DataLabel": {
      "fontSize": 10,
      "baseline": "bottom",
      "fill": "#333333"
    }
  }
}`

**Comment by dm-p** [comment]
Hi @DaveTN - thanks for the detail in this issue. As you originally asked this on another forum (and I've been away on leave to get to it before they closed it), [I've answered in a bit more detail there](https://forum.enterprisedna.co/t/vega-issue-autosize-fit-y-and-horizontal-scroll-bar/40004/7). In short, I think that due to how we're dealing with a container of dynamic size (in that Power BI supplies the height and width values), Vega possibly doesn't quite calculate the available width correctly in this case and it's set outside of the bounds by the default padding x2 (for both left and right sides). Hopefully the solution on that post can work for you (setting `width` to the `pbiContainerWidth` signal minus the total default padding).
