### ISSUE TITLE
Visual is loading. Please wait...

### ISSUE THREAD

**Issue by sm-thirdman** [deneb-viz/deneb#329]
Hi,

When the visual is loading it shows the message: 'Visual is loading. Please wait...'.

From the code I can se this message is set in resources.resjson, line 165:

"Initial_Loading_Message": "Visual is loading. Please wait...",

Where I need to get to:  Either the above message is not shown or a replacement message, same meaning but different language, is shown instead.

I assume I cannot just edit the text, as I would have no way of packaging the variant for deployment to the PBI service and maintain it being MS certified.

Would it be possible to have a config option to either turn off this message or replace the text?  Or is there a way I can do this myself?

**Comment by dm-p** [comment]
This screen is a placeholder until the visual has initialized. Even if we were to expose a property to change the message, it would not be accessible until after this point, so as you have identified, a suitable localization string would be the way to solve this based on the architecture.

I would suggest creating a resource file for your desired locale and adding the desired value for this key in a PR. Alternatively, if you can provide what you want plus your locale here, I can add to the list of things I'm doing for 1.6. 

Note that in terms of an ETA: whichever solution we go with, I can't submit to AppSource presently, as MS have changed some certification rules and these have not been trivial to fix in the current codebase. I am working on getting this unblocked ready for the 1.6 submission.

**Comment by sm-thirdman** [comment]
Hi, thanks for coming back to me.
I have not done any development work for many years, before things like GIT and Javascript existed.  I mention that to explain why some of my questions may seem a bit simple. I'm assuming PR is 'pull request'?

What I'm not clear on the locale file is what sets this in PBI.  My usage is Power BI embeded.  I'm not sure what sets the locale when the report is run, if this is a service/tenet-wide setting or a per report call from the embeded code.

The locale I'm needing doesn't exist on the Power Bi service, it is very niche (it is Sctosih Gaelic).

When you say 'initialised', does this include the call to the PBI host and getting the data, which in my case is DQ?

**Comment by dm-p** [comment]
Apologies - yes 'PR' would be Pull Request. In this case, it would have been referring to making a folder for the locale and a `resources.resjson` file with the relevant changes. To my knowledge, valid locale codes are only for [locales supported by Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/supported-languages-countries-regions), so may not be a possible avenue of attack.

Regarding initialization, it may be easier to provide you with a reference to [how visuals integrate with Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/power-bi-visuals-concept) to confirm, but the short version is this:

1. When a page is loaded, visuals go through an initialization phase (`constructor`).
    - At this point, they have access to the locale information (and some other things), but not visual properties.
    - Properties are only available when data is present in the visual. This is not established by Power BI until step 2.
    - It is at this point that Deneb displays the 'Loading...' message, as we aren't yet fully initialized, and this is a UX placeholder until Power BI does more work.
2. Power BI then executes an `update` method after initialization. 
    - At this point, we get access to properties and data and can process these.
    - Therefore, it's not possible to customize the 'Loading...' message via a property, because Power BI can't get its value until this stage.

As such, it would not be possible to change the message, short of building your own version with your own revised one. You have a couple of options, if you can work without the certified version, as this is tied to AppSource. The standalone version is the same, but allows loading of images and data from remote locations and isn't connected to AppSource, so Power BI won't replace it with that version:

1. Make your own standalone build the correct way:
    - Check out the code from the repo.
    - Go through the prerequisites for [setting up a development environment](https://learn.microsoft.com/en-us/power-bi/developer/visuals/environment-setup).
    - Run `npm i` to install dependencies.
    - Change the value for the `Initial_Loading_Message` localization key in `sringResources/en-US/resources.resjson` and save.
    - Run `npm run package-standalone`, which will generate a standalone version of the visual in the `dist` folder. Note that `npm run package` will package using the same ID as the AppSource version and as such, Power BI will recognize this and replace it with the latest one from there.

2. Hack the standalone .pbiviz (not supported):
    - Use a compressed file manager (e.g., 7Zip) to open the standalone .pbiviz.
    - Open the `resources/Deneb_STANDALONE*.pbiviz.json` file for editing.
    - Search for the `Initial_Loading_Message` token and replace its value with your desired translation.
    - Save the file and replace the one in the .pbiviz archive with it.
    - Load your visual into the workbook by importing from file. If you have a report page currently open with the Deneb visual, you will need to navigate to another tab and back again to make Power BI go through the initialization process (therefore reloading the new version).

Note that the standalone versions also don't self-update so if new versions of Deneb are published you may need to decide if you need to repeat the process for keeping your version up to date.

You can download the latest standalone version from the [Releases section of this repo](https://github.com/deneb-viz/deneb/releases) and learn more about it [on Deneb's documentation site](https://deneb-viz.github.io/getting-started#standalone-version).

**Comment by sm-thirdman** [comment]
Hi,

Many tbanks for coming back to me on this.  I will try out building the standalone/no certifeid version and see how it goes.

My other angle was to try and improve the data load performance, but it is pretty much as fast as it is going to get.

Many thanks!

I will try the

**Comment by dm-p** [comment]
From some investigations, it looks like there is a locale code for Scottish Gaelic (gd-GB). 

I don't have any experience with Power BI embedded, so you may need to advise me here as to whether there is a capability to specify the report or user locale. If there is and it can be supplied to a Power BI visual, then we could add a suitable resources.resjson file to the build with the translation you need.

I'm not sure if this will be possible from embedded, but if it is, I will just need the translation you need. The earliest I could do this is in v1.6, and this is still a few weeks off completion, but I might be able to provide you with an alpha build to test if it works before I submit to AppSource (as this is a lengthy process and takes ~5 weeks to go through certification and deployment by MS).

**Comment by sm-thirdman** [comment]
Hi, sorry for the delay, I have been away.

I have the translation:
Visual is loading. Please wait … | Tha ìomhaigh a' luchdachadh. Fuirichibh...

What I don't know yet is if this can be done per report execution from embedded, I'm waiting on someone else to investigate this.

**Comment by sm-thirdman** [comment]
Hi,

Just a note to say I had to go for the hack option, option 2, above in the end.  I tried the compile option, but I got the following error:

```
> package-standalone
> npm run template-schemagen && node bin/package-custom --mode standalone


> template-schemagen
> typescript-json-schema ./src/features/template/schema.ts IDenebTemplateMetadata -o ./schema/deneb-template-usermeta-v1.json --required --topRef

Checking for package configuration...
Configuration {
  pbiviz: {
    visual: {
      displayName: 'Deneb (Standalone Version)',
      guid: 'STANDALONE{0}'
    },
    assets: { icon: 'assets/icon_standalone.png' }
  },
  'deneb-config': { features: { enableExternalUri: true } }
}
Using configuration for [standalone]
Updating pbiviz.json with configuration...
C:\Users\Sam\Dropbox\Work\Code\Deneb\deneb-1.5.1.0\bin\package-custom.js:58
                `$1${suffix}#${commit.shortHash}`
                                      ^

TypeError: Cannot read properties of undefined (reading 'shortHash')
    at getPatchedPbiviz (C:\Users\Sam\Dropbox\Work\Code\Deneb\deneb-1.5.1.0\bin\package-custom.js:58:39)
    at C:\Users\Sam\Dropbox\Work\Code\Deneb\deneb-1.5.1.0\bin\package-custom.js:79:13
    at C:\Users\Sam\Dropbox\Work\Code\Deneb\deneb-1.5.1.0\node_modules\git-last-commit\source\index.js:38:7
    at C:\Users\Sam\Dropbox\Work\Code\Deneb\deneb-1.5.1.0\node_modules\git-last-commit\source\index.js:13:7
    at ChildProcess.exithandler (node:child_process:427:5)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:323:12)

Node.js v18.17.1
```

**Comment by sm-thirdman** [comment]
Hi,

On Power BI Embedded it is possible to set the locale per report.  However, if the PBI Service doesn't support that locale it just defauls to en-US.

**Comment by dm-p** [comment]
To confirm regarding your attempt of option 1: did you check out/clone the repository to your machine via Git, or download it? From reviewing, I perhaps wasn't explicit in that the repository should be present in this manner. The build script needs to be present in a Git repository (to get the last commit ID), which is where it's falling flat. Of course, if you did do that already, then I am unsure what the problem might be. I should probably change this so that if the last commit ID is unavailable then it just coalesces an empty string to the package name rather than failing. 

Regarding the second point re: embedded, I will add the translation for the specified locale, and you should be able to test whether it works for explicit setting of locale in an embedded report when alpha builds of 1.6 become available (I'll advise you when this will be available; ETA next week). If it doesn't (or you need the Service option, which will likely default to en-US), then I appreciate this may not be possible, but hopefully if you can do the explicit setting of locale then you can stay with the current production version when it moves through to AppSource rather than having to maintain your own specific process.

**Comment by sm-thirdman** [comment]
Hi,

I downloaded the source from latest and then 1.5.1 as zip, unpacked and ran through the steps.  As I say, my programming life finished before Git/JS was a thing, so the correct way to do things is unfamiliar.

I then downloaded the standalone version and edited the resource file directly.  This version I loaded directly into PBI.

On locale/embedded:

From what I understand from the developer, seeing the local by report via embedded set up code allows Gaelic, or any other locale to be set.

However, if the service doesn't support this locale it changes it back to US default.

Part of the overall solution would be to get MS to provide the Gaelic locale I suspect.

**Comment by dm-p** [comment]
In 1.6 we ended up removing the 'loading' message on initialization, which should mitigate the need for this feature. As such, I'm closing, but if you feel there is still work to be done, this can be reopened with any requirements based on the current version.
