### ISSUE TITLE
Segoe UI font isn't rendering correctly only on a Mac (in Chrome or Edge browser on PowerBI.com) and only inside Deneb visual. 

### ISSUE THREAD

**Issue by mlongoria** [deneb-viz/deneb#341]
I have created a Deneb visual that renders correctly for me in both Power BI Desktop and PowerBI.com. A client opened the report in PowerBI.com using Chrome on a Mac, and the fonts I specified are not working and have fallen back to some kind of serif font. 
What I see: 
![image](https://github.com/deneb-viz/deneb/assets/20218384/e4020f0f-a05c-455e-9b52-15f08d06da80)
What they see: 
![image](https://github.com/deneb-viz/deneb/assets/20218384/003fdf37-3ad7-491f-9a47-543e1e00c479)

I have my fonts on the rest of the report set to Segoe UI and I think it renders fine outside of Deneb. But inside the Deneb visuals, Segoe UI isn't rendering. 

I had a coworker with a Mac reproduce the issue in Chrome. He sees the serif font. If I change the font to Arial, the font changes correctly and the Mac users see the Arial font.

My spec and config file are here: https://gist.github.com/mlongoria/7d836a3989aa7ebad6353ca9b2256d2e. Did I do something silly that I am not catching?

**Comment by dm-p** [comment]
It's very possible that "Segoe UI" is not sufficient as a font name on Mac (I don't know for sure; don't have one to test with). If using the font selector in the properties menus, they add a bunch of [fallbacks](https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/). MS uses this as the full value for Segoe UI in the Power BI Service:

 `Segoe UI, wf_segoe-ui_normal, helvetica, arial, sans-serif`

It could be worth trying this as your font configuration and it might work, e.g.:

````json
{
  ...
  "text": {
    "font": "Segoe UI, wf_segoe-ui_normal, helvetica, arial, sans-serif",
    "fontSize": 30,
    "fill": "#605E5C"
  },
  ...
}
````

**Comment by mlongoria** [comment]
That worked! Now I know to look out for that in the future. Thanks for the help.
