### ISSUE TITLE
Question: is it possible to use different colors in a radar chart?

### ISSUE THREAD

**Issue by LuciannaFG** [deneb-viz/deneb#387]
Hi everyone! 

I am trying to create a radar chart, using Vega language, where each dot representing  category has a different color but the filling color to be a single color. At the moment, I am able to do one or the other (never both at the same time). Do you think this is possible? Bellow I show the two examples and the desired chart would be both overlapping. (Thank you so much in advance for any assistance you can provide!)

 
![image](https://github.com/deneb-viz/deneb/assets/36709188/e9ec9158-6d45-4473-92fa-f23774aeb2e1)

![image](https://github.com/deneb-viz/deneb/assets/36709188/f6c3bdd8-c632-4f53-9501-d1ebdb21553e)

Here is part of the code that I'm trying to modify without success :

"data": [
    {"name": "dataset"},
    {
      "name": "keys",
      "source": "dataset",
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["Risk_Area"]
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "angular",
      "type": "point",
      "range": {"signal": "[-PI, PI]"},
      "padding": 0.7,
      "domain": {
        "data": "dataset",
        "field": "Risk_Area"
      }
    },
    {
      "name": "radial",
      "type": "linear",
      "range": {
        "signal": "[0, radius]"
      },
      "zero": true,
      "nice": true,
      "domain": {
        "data": "dataset",
        "field": "value"
      },
      "domainMin": 0
    },
    {
      "name": "color",
      "type": "ordinal",
      "domain": {
        "data": "dataset",
        "field": "Risk_Area"
      },
      "range": {"scheme": "category20"}
    }
  ],
  "encode": {
    "enter": {
      "x": {"signal": "radius"},
      "y": {"signal": "radius"}
    }
  },
  "marks": [
    {
      "type": "group",
      "name": "categories",
      "zindex": 1,
      "from": {
        "facet": {
          "data": "dataset",
          "name": "facet",
          "groupby": ["Risk_Area"]
        }
      },
      "marks": [
        {
          "type": "line",
          "name": "category-line",
          "from": {"data": "facet"},
          "encode": {
            "enter": {
              "interpolate": {
                "value": "basis"
              },
              "x": {
                "signal": "scale('radial', datum.value) * cos(scale('angular', datum.Risk_Area))"
              },
              "y": {
                "signal": "scale('radial', datum.value) * sin(scale('angular', datum.Risk_Area))"
              },
              "stroke": {
                "scale": "color",
                "field": "Risk_Area"
              },
              "strokeWidth": {
                "value": 10
              },
              "fill": {
                "scale": "color",
                "field": "Risk_Area"
              },
              "fillOpacity": {
                "value": 0.1
              }
            }
          }
        },

Kind regards.

**Comment by reijar** [comment]
I think you need one mark for the line and another for the markers. 
Using this [radar chart example](https://vega.github.io/vega/examples/radar-chart/), 
I added a new color scale for the markers and 
duplicated the "category-line" part in "marks" to "marker". 
There 
"type" is changed from "line" to "symbol", 
"scale" for "stroke" and "fill" is now the new color scale and "field" is the dimension ie "key"

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATONABONHJnaT0AQQAEipLKSLtsQ5m1wAHkgQ4ANnCnaIMNgHca4stoQNbau3DasjQIcOIQ6hDaHtpIuvo0SLbatkgAnmwMmJTSIO6y9GgALAAMJTLwNGRYxWUyOPrBnrUySFlsEQBecGigmGk4PejiEj0yUBKYSB4QaCANsk1kIAC+MhFk4kmzqADaoFuhc3rBDLMyDDgGmEN5NAUw2gTaAEyrALoy1yh7B9a3UyY9lyxCSDAUaH2IAA1nA0nNYWkALQlEFgoYARgAnOMkDcyGxFPDUCU1qBEQi4UiMWjbOC0C8Xrj8YTiaSpOS4ZTkW8ZKC6ZiiszyKy0OzOcSYVSAMy0+moaUADmFBKJYrJUsliKRRTlQxe0pVopJGop6G1Aj1aAERrVJo5mu5SIAbFbUC8AOy2tmmrnmqmovnotAYw0gKB4kV2jG+rVUmlBgUhpnhyOq4kxh1mzVI3kgfnyoopiMs6Oxp2yxPy0PekPl-3I3VVobO2uoTMSp2W5shm2p0sZ+s51091DK-tRwfvDWHW6I84gMQMRRQAFIIFjECYPThABmhIQkL6A1uSDIZEUfBuuQvmRwTGJu0d05f6wj9h2UNncyQnl8hlyfpBjmHA2A8TBch3MghlADYtlsOZdiRAAFABJRw0PeVZ6kaDxlhJSg+1kNhkA8Xo5DxH4t3XYEZF3Gg4FsWRuVWGd-mOBIkkAk85lsDw4AAmQoJgxcqngxDyniU4ICwtYQG6RQ2DQbdwRkcQaFXNBd22Bw5BI6YNFAb45kBWiQHoxjmPQAsejk4jSPEABZMj7T+I50AmWxCW44D0EJJouK+fSXKMyiTJozcLKYuYS0nbCQGEyEQAAYiYWQ0rS3JkqxZ0cpykBpwdb90GQRRYSMTzvJkIDbn8jxAr0hzyOM9BTMihjoobeLEtQWDYEQW5YvTDFURWFZPhAMIJnkciwhuRRyIsci4K49AThoM54uJWCxNWhKEk2sa5NK6FP2PXyQFvS5cmKidVQYhdOg8eQlvbOjFMPXrzKQVcIK+lrqI3G72PQbTfpvRTLgfJKhtFadjsMU6jy3Hj0D48RN1u2GiSRdHIo+5qwtBn64AguSprYGavrmuAFq+8DadA1Jry+mzeP4wwkSgLyIDgZi5NenbNj26AkjgAAKABydakklxxrgYBBKBsgBKbQACpjA6cXRfsKXfzIf9FDloI8UVyhERVlWtuW3aEPQXWJelzjbBNhWldVjWnA8HX3ydg2jbds2lct625Igbc2FhZa-ZitgvIWuiOqsu7RXDyPYQAdXuQpWeDds5Po2x7b6sW44T3IopT7H4ULmhi4AeQaKA6G2-N85KSgXiOjUarmCA0gQJh4+B9yQBO2nK4J-6ie+8HyfEaaRJpunQAZxQmcjci2bRjnFC5nm+fiwXROF+3Fz9qWZdd+Xg+V9E1c1iYIF9sX9b-VJjdvzBzdDm2vpWufR2V8XZBx-h7B+XsIjiFfnrSWAdP5gN-nCK28UI6KWjgA2OJVEa0y1hXJOlkWLpwwXAbODxt750zOZeuJcL5lxwWVPBlVE40KIV1Oujdm6t0oUmAiAhw40G6Lw+ULwyg9wdH3VqlgIJqRBu3AUSIbgWFkeZaeoUpgxTTKyXG-F4oUypqAFei1bZnzmO7SgS05Jt0AeYu+tdqoyNMeJdAFiLFszkkkMSIjBrGLkkwJAvM8Y+LmAge4shgScLoTvEAQIfrQlYmNQq51biKF8JjeR18kQXnuFPEihNNENlmHJJ64gXpihkAY5e4h5omLznw9kIA2470aRYN4AC7YcWkl7Z+sD-Yf0MEgkOKCw4yDSO0oWLj9rdM1tAvp79DaIO-sgtIqCSFRxEjEvi1RMAXnSGgjOZCc4wBCQXI6kjUZbicXIse2pUhMEYnkz6GiqLzniqU8pb1JqL0ptU2pX0T62PQOLdaZxtAAGptACEflrF+wD4EDK-qbcBFsRn-0mXtEFB0oiQuhVAn28KEGDOWcM1ZoyrkqPIlXYhrRtkaChDcCOP4mBwsvgixZxLkUrKttoAAfNoNCTxXhugSlUGoGotlwF3GTCaASgl6N+FcplDs2VEqRRYy2fLtCBgUfKLcbAcDYT6AoP69C4FqqGai1Z2gAC8NrtUirCYsSJDoYnD2wPk8aSdi6nNiakKACTC6TEznAMVf1QBuvjvzc5KT2YY1HrVLItNdHxvevkmehTpmJFsNk5Q-NKk-MMd8-5a8amM3jlvepeq8ac25h0I+AsqXJzmG09FbDOpNLeOszBEb84gG2VgPZDjFyHPIbnXtfCYxHWnEAA)

<img width="301" alt="image" src="https://github.com/deneb-viz/deneb/assets/10187986/94ef901d-3ce6-480d-baf7-fa16955c538f">

**Comment by LuciannaFG** [comment]
That was incredibly helpful!
Thank you very much, @reijar . I was totally lost and modifying the wrong part of the code.

Thanks.
