### ISSUE TITLE
Data Point Resolution After Transforms

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#390]
I know that if you use Vega transforms in your spec, you lose the row context and subsequently the ability to have resolved tooltips or drill through as described here.

https://deneb-viz.github.io/interactivity-tooltips

I was wondering - is this a hard limit or would it be possible to enhance Deneb to allow it to resolve even transformed datapoints using something like TREATAS()?

**Comment by dm-p** [comment]
As long as you can ensure that the `__row__` field can reach your mark's datum, Deneb can resolve the data point back to Power BI. In some cases, you may need to explicitly include the `__row__` column as the output of any transforms that continue to support the granularity level matching the original dataset that Power BI provides. 

Sometimes, adding the `__row__` field in a layer or similar will often ensure that (Vega-Lite certainly) will automatically include it in the datum.

What's tricky is having to track this back in the absence of the `__row__` field. The Vega view doesn't explicitly have an API to track lineage to a source row, so we're a bit stuck. I've coded some simple heuristics in the event of faceting or aggregation where we try to reverse-lookup all data points that fall under that grouping and apply them, but this is very simplistic. 

It's possible that we can extend this in some scenarios. Is this probably what you're getting at with the `TREATAS` analogy? I'd probably need to see an example to understand further whether it could be eligible for such treatment. Still, there may be a way for us to specify a particular way to look up original data based on a user's preferences if we can't do anything smart.

**Comment by PBI-David** [comment]
Thanks Daniel and yes, that's exactly what I meant. I thought we may need to use TREATAS() to re-establish lineage but perhaps we don't. I will play with the __row__ field and try to come up with an example to better illustrate the problem. Thanks again.

**Comment by PBI-David** [comment]
Hi Daniel - I have an small example of what I'm talking about now. Incidentally, this also presents the same problem as https://github.com/deneb-viz/deneb/issues/391.

In the attached is a super simple force directed graph. In order to render the nodes on screen, the original dataset has been through several transformations and seems to have lost any relationship to its original context. If I click a row in one of the tables, then it cross filters the Deneb visual perfectly. However, what I would like to achieve is the inverse so that when a user clicks a node in Deneb, it filters the corresponding rows in the table visual. 

If I hack __row__ or __selected__ to the transformed dataset in order to give it values that match the original __row__ assigned, it seems to have no effect. Is there a way to hack this and restore some kind of context to make Deneb cross filter PowerBI visuals when the dataset has been transformed so many times?
[Force Directed Graph - Daniel.pbix.zip](https://github.com/deneb-viz/deneb/files/13284292/Force.Directed.Graph.-.Daniel.pbix.zip)


![image](https://github.com/deneb-viz/deneb/assets/86846675/4d7db4ec-f583-4c2a-80e6-309ef4f6583b)

**Comment by PBI-David** [comment]
Solved by https://github.com/deneb-viz/deneb/issues/394
