### ISSUE TITLE
Deneb still showing old verison despite updated

### ISSUE THREAD

**Issue by RiyadBkhsh** [deneb-viz/deneb#392]
Deneb visual is already updated but is not showing any change when trying to use it. Restarted the Power BI no improvement. 
![Screenshot 2023-11-08 155639](https://github.com/deneb-viz/deneb/assets/87756356/0f3a44ee-6bc0-4520-a7b5-d6000e32ac19)
![Screenshot 2023-11-08 155709](https://github.com/deneb-viz/deneb/assets/87756356/0eebe17d-3ff9-44f9-b2e2-eff4530db5c5)

**Comment by dm-p** [comment]
Hi there - when MS approves a visual, the AppSource listing will update immediately, but it will take 2-3 weeks to deploy to all reports fully. Visuals registered in AppSource are deployed from a CDN that MS manages. If you want a more detailed read, [OKVIZ has a great blog post about the process](https://okviz.com/blog/updating-power-bi-custom-visuals/).

If you are trying to shortcut the process by manually loading the AppSource version from a file, this won't work, as Power BI checks the ID against AppSource and will deploy the version they have on their CDN. This is how visuals are automatically updated without you updating them manually. From the looks of things, your CDN is still serving 1.5.1. My Power BI reports are still showing 1.5.1, too, but some folks have reported seeing the new version in their reports. Approval was this time last week, so it could take up to 2 more weeks for some users.

If you want to use the new version before your CDN cuts across, you have three options:

1. [Use the standalone version](https://deneb-viz.github.io/getting-started#standalone-version), which is disconnected from AppSource.
2. Add the .pbiviz as an [organizational visual](https://learn.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-organization).
3. [Put Power BI Desktop into developer mode](https://learn.microsoft.com/en-us/power-bi/developer/visuals/submission-testing). Note that this will only work for as long as the current workbook is open and will revert to the CDN version next time you open it.
