### ISSUE TITLE
Stuck on initialising when there is no data.

### ISSUE THREAD

**Issue by jeanny-z8** [deneb-viz/deneb#393]
Since the update to v1.6, visuals that do not have data for the selected date range gets stuck initialising:
![image](https://github.com/deneb-viz/deneb/assets/128969920/8494ff40-09fe-4e3a-9388-88d0df113ca4)

If you adjust the date range to a period where there is data, the visuals resolve, and then going back to the previous (empty) date range, the visual shows blank as expected, rather than the initialising bar:
![image](https://github.com/deneb-viz/deneb/assets/128969920/c95c7e32-6e1e-40be-93b8-ec64372cb6d2)

This behaviour repeats any time the report page is reloaded.

**Comment by dm-p** [comment]
I'm sorry for the inconvenience. [There is a new alpha build available for download](https://github.com/deneb-viz/deneb/releases/tag/alpha) - can you please test this and confirm your issue is fixed? If so, I will arrange to submit to MS for certification.

**Comment by jeanny-z8** [comment]
That looks to have fixed the issue! Thanks for looking into it so quickly.

**Comment by dm-p** [comment]
Thank _you_ for the report and for helping to confirm the fix! 

Version 1.6.1 has been submitted to MS for certification - unfortunately, things slow down at their end at this time of year, so hopefully, it won't be too much longer than usual. I'll advise how this is going as I hear about the progress.

**Comment by dm-p** [comment]
1.6.1 has been approved for certification and the AppSource listing has been updated. This means that the visual should be live in your reports within 10 working days (as it takes a while for MS to do final deployment across all regions). 

Thanks again for finding, reporting and helping to verify this works as intended :)
