### ISSUE TITLE
What to do about the 'Initializing' status in Deneb?

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#395]
The initialization message is built using the standard Fluent UI light theme, and as such, this will have an opaque light background. This causes issues with reports that have different, or darker colored backgrounds, e.g.:

![image](https://github.com/deneb-viz/deneb/assets/10572054/fdc81327-f15f-4eb1-80c3-c90c16181f71)

We can't make this configurable, as it is put in place when the visual itself is initialized, and we don't have access to the properties at this time (we get them when the first update comes from the main window).

I liked having this message here because it implied that something was going on while we were waiting for Power BI to catch up and get our dataset. Other visuals just use the spinner in the visual header that Power BI provides, and I guess that we could too, in order to avoid the cosmetic issues.

As such, I'm considering removing the message to avoid these issues with different report themes. Does this make sense for people, or is it useful and you have a particular need for it? Consider that I can't make its display configurable due to the aforementioned limitations with properties not being available, so it would be one way or the other.

**Comment by JamesDBartlett3** [comment]
Great question! Can it be configured so that the area in question is transparent while initializing, and then opaque when it has finished initializing? If so, report developers could put a "loading..." spinner animated gif on the report canvas right underneath the visual if they think it's necessary. That way, the report users will see the spinner, but only while the visual is initializing.

**Comment by dm-p** [comment]
I think that this could be a good compromise. One thing to consider is that we don't get the properties until the end of the initial query, so we may have a noticeable lag for a large dataset. The message would then only be visible for the length of time needed to process the dataset and specification from this point onwards, so may not be noticeable for simple specifications and low cardinality datasets.

We would potentially then have the option to allow the user to configure:

* Visibility of status message
* Message text / visibility
* Background color
* Text color
* Progress bar color / visibility

**Comment by JALTableau** [comment]
I have this message when the data is not present. For example, I visualize the interruptions in a production line (see below example) 
![image](https://github.com/deneb-viz/deneb/assets/47753705/f8178d81-b073-4ccd-baef-6fcea20eff89)
but when is not an interruption the visual shows below image
![image](https://github.com/deneb-viz/deneb/assets/47753705/baeb1105-5437-4764-b4bc-432900795fa5)
Is any way we enable the visual when it is data and disable it when it is empty using a DAX measure?

I appreciate in advance your time and any suggestion.

**Comment by dm-p** [comment]
@JALTableau please see #393. This is a bug and a fix (v1.6.1) is in the process of being certified by MS. If you need a build in the interim (as it can take a few weeks to fully certify and deploy), you can download the alpha build linked in that issue. Please note that the alpha build is effectively a unique visual and not tied to AppSource (and is therefore uncertified).

**Comment by dm-p** [comment]
Now that change has been made to remove the status, and we're planning to make some of the other phases asynchronous, it doesn't make sense to carry on with this, so closing.

**Comment by JALTableau** [comment]
Thanks
