### ISSUE TITLE
Tooltips not working in v1.6.1.0

### ISSUE THREAD

**Issue by jeanny-z8** [deneb-viz/deneb#408]
Since the latest version, tooltips encoded in Deneb visuals isn't working.

I've checked a few different visuals, and none of them have working tooltips.

I've checked with a few standalone versions, and I can confirm that tooltips works in the standalone v1.6 and 1.5.1, however they don't work in the alpha build of v1.6.1.

Please let me know if there's any more info I can give to help.

Cheers, Jeanny.

**Comment by dm-p** [comment]
Hi, this is a duplicate of #407 - please refer to that issue for the workaround and for that link to the standalone build that has been submitted to MS to mitigate.
