### ISSUE TITLE
Deneb not accepting Vega Lite condition in encoding

### ISSUE THREAD

**Issue by david5053** [deneb-viz/deneb#411]
I am trying to add a condition to Vega Lite in Deneb that dynamically sets the y-axis maximum to 100 when the indicator selected in Power BI is a percentage, else retains the default y-axis maximum behaviour. I have tried various ways of adding a condition to the encoding section, but wherever I place it, it is rejected by Deneb with error message "should NOT have additional property: condition". I can't find a way around this, no matter where I place the condition. Can you advise what I'm doing wrong?

![Picture1](https://github.com/deneb-viz/deneb/assets/153733568/df940bd9-e353-482e-8795-defe867373ad)

Below is the relevant section of code:

  "encoding": {
    "x": {
      "field": "areaname",
      "type": "nominal",
      "sort": {"field": "pracbarorder"},
      "axis": {
        "labels": false,
        "ticks": false,
        "title": null
      }
    },
    "y": {
      "field": "val",
      "type": "quantitative",
      "axis": {
        "ticks": true,
        "title": null
      },
      "scale": {
        "condition": {
          "test": "data('dataset')[0]['unit']=='%'",
          "domainMax": 100
        }
      }
    },
    "color": {
      "field": "pracareagroup",
      "type": "nominal",
      "legend": {
        "orient": "none",
        "legendX": {
          "expr": "width-320"
        },
        "legendY": -100,
        "labelFontSize": 13,
        "labelLimit": 300,
        "symbolOpacity": 0.75,
        "title": null
      },
      "scale": {
        "range": {
          "field": "legendColor"
        }
      }
    }
  },

![Picture2](https://github.com/deneb-viz/deneb/assets/153733568/2b9a56f3-79ac-44a5-b9bc-6d7d30c6ea9f)

**Comment by Giammaria** [comment]
Hi @david5053, try something like the following. Note, the params section and the transform section is purely for toggling to as a demonstration. The important pieces are in the _scale_ and _axis_ properties under the _y_ channel


`{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": 200,
  "params": [
    {
      "name": "categoryCValue",
      "value": 0.75,
      "bind": {
        "input": "range",
        "min": 0,
        "max": 1.5,
        "step": 0.1,
        "name": "Cat C Value"
      }
    },
    {
      "name": "yAxisAsPercentage",
      "value": true,
      "bind": {"input": "checkbox", "name": "Y-Axis as %"}
    }
  ],
  "data": {
    "name": "dataset",
    "values": [
      {"category": "a", "value": 0.25},
      {"category": "b", "value": 0.35},
      {"category": "c"}
    ]
  },
  "transform": [
    {
      "calculate": "datum['category'] === 'c' ? categoryCValue : datum['value']",
      "as": "value"
    },
    {"calculate": "yAxisAsPercentage ? 'percentage' : 'number'", "as": "unit"}
  ],
  "mark": {"type": "bar"},
  "encoding": {
    "x": {"type": "nominal", "field": "category", "axis": {"labelAngle": 0}},
    "y": {
      "type": "quantitative",
      "field": "value",
      "scale": {
        "domainMax": {
          "expr": "data('data_0')[0]['unit'] === 'percentage' ? 1 : null"
        }
      },
      "axis": {
        "labelExpr": "data('data_0')[0]['unit'] === 'percentage' ? format(datum.label, '.0%') : format(datum.label, '0.2f')",
        "tickCount": {
          "expr": "data('data_0')[0]['unit'] === 'percentage' ? 11 : null"
        }
      }
    }
  }
}`

**Comment by david5053** [comment]
Hi @Giammaria, thanks for your helpful suggestion. The problem with setting domainMax to null is that is doesn't restore the default behaviour.

If you remove the scale section of your code, you'll see the default behaviour is for Vega Lite to determine an appropriate value for the maximum and to show it at the top of the y-axis.

![Picture1](https://github.com/deneb-viz/deneb/assets/153733568/28ac1fe0-535d-463d-8e26-49f73c7e0572)

When domainMax is set to null, the axis is often cut off without a maximum value being show.

![Picture2](https://github.com/deneb-viz/deneb/assets/153733568/ac8f5559-9e73-4b21-b8b5-0056881428d4)

I'd like to create a condition that only changes the default behaviour of Vega Lite if the unit is a percentage, as I don't want the y-axis to be cut off without a maximum value being shown.

**Comment by david5053** [comment]
I have worked it out!

If setting a domainMax, you also need to explicitly specify "nice": true to restore the default behaviour so that the axis ends on a nice round value. So @Giammaria's code should be modified as below: 

![Picture3](https://github.com/deneb-viz/deneb/assets/153733568/4a15c7ec-dfbd-42be-8ca7-c530cc0ed358)
