### ISSUE TITLE
Gantt Chart Enhancement

### ISSUE THREAD

**Issue by iwassammasood** [deneb-viz/deneb#416]
Is it possible to change the date range (timeline on the top) as right now it is displayed as day by day, Is it possible to make it monthly or quarterly? along with the year displayed next to the month's name. That'd be a game-changer for this chart. This has been the most asked and requested request by the individuals on the Reddit post.  @dm-p

**Comment by Giammaria** [comment]
Hi @iwassammasood. I'm assuming that you're referring to the gantt created by @pbi-david. If so, fortunately he's one of the Deneb community experts.

Please check out the [Support](http://localhost:5173/editor/
) page on the Deneb documentation site for instructions on how to best obtain support.

**Comment by PBI-David** [comment]
I think this one has already been answered by someone else so I believe this issue can be closed. 

https://community.fabric.microsoft.com/t5/Desktop/Deneb-David-Bacci-Gantt-Chart-How-to-modify-daily-timeline-to/td-p/3488350
