### ISSUE TITLE
Tooltip showing false instead of value

### ISSUE THREAD

**Issue by remsidave** [deneb-viz/deneb#429]
Hello, first of all thank you for such an amazing visual!

The following Vega-Lite code in Deneb shows false instead of "0001" as tooltip but works fine in [Vega Lite online editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUAItBvCAEwAMZALALQUCM9DIANCAGIQDGUA9gCcAnqQpiW7AGqpM8BmIC+rQsVKUazemTace-YaQCCAIQCsFHdPQk48ikpVQb5KnUb0AzDq69BIuCBijJYyNnYOIEROaq6aFNTeen5GZhZSoXKKALpKIAC2EAIA1qQADnwAlgB2UDoYVdx8YNUA5vCgAB7tIABmFRgoYKRRJOxQQqXOTnnlAqgguf6gfQNDAVayYxPOAI5oEDUVMFAViCS5-HwoJ6V4y-2DpD76IluTpFV8edXzCjkKQA)

`{
  "data": {
    "values": [
      {"Date": "2024-01-01", "Factory": "0001", "Value": 100},
      {"Date": "2024-01-02", "Factory": "AB50", "Value": 100},
      {"Date": "2024-01-03", "Factory": "0001", "Value": 100},
      {"Date": "2024-01-04", "Factory": "AB50", "Value": 100}
    ]
  },
  "mark": "point",
  "encoding": {
    "x": {
      "field": "Date",
      "type": "temporal"
    },
    "y": {
      "field": "Value",
      "type": "quantitative"
    },
    "tooltip": [
      {
        "field": "Factory",
        "type": "nominal"
      }
    ]
  }
}
`

![image](https://github.com/deneb-viz/deneb/assets/82058781/9ac4bbb2-7466-4c5f-9f28-8603d26ed757)

This is just a minimal reproducible example, we see the same behavior in a real report where strings like 0001 are mixed with other more typical strings like AB50 in a power bi column formatted as text as input for Deneb. Due to company rules I am not allowed to share any files, otherwise I would have included a sample file.

I'm using Deneb 1.6.2.1 in Power Bi Version: 2.127.1080.0 64-bit (March 2024)

**Comment by dm-p** [comment]
I'm sorry for not getting back to you sooner. I tried this in Deneb 1.6.2.1 on my machine, and it works as I would expect:

https://github.com/deneb-viz/deneb/assets/10572054/9c24aca6-1121-4e1f-ba5e-f6187c9166e4

The only discernible difference was that I was on the February 2024 build of Desktop. I've updated this to April 2024 (2.128.952.0), and it continues to work for me. 

Can you please confirm if this is still an issue for you? If so, do you have any further info you can provide about your setup, such as:

* If you're using the Power BI tooltip functionality (Tooltip handler = ON) or the Vega tooltip utility (Tooltip handler = OFF).
* Whether doing this from a brand new visual or an existing one.
* Whether Desktop is installed from the download or from the Microsoft store (this shouldn't matter, but you never know).
* Locale information.

**Comment by remsidave** [comment]
Thanks for your reply. The issue is partly still here. I'm on Power Bi  2.128.751.0 64-bit (April 2024) now.
It works as expected when creating a new Deneb visual with the code that includes the data. However, if I create a new Deneb visual and use the same Data from the Power Bi data model, then the tooltip still shows False for '0001'. Funny enough, if I paste the code including the data in the visual initially created with the data from the Power Bi data model, then the tooltip also shows False for '0001':


https://github.com/deneb-viz/deneb/assets/82058781/48f8a67e-5969-418a-b5ae-25b4a931157b

To your questions:
- Tooltip handler is on
- From a brand new visual
- I don't know about the installation source of power bi. This is handled by our IT department which I'm not part of. Updates are installed without my intervention.
- I have set Power Bi to use windows default language and model language to use application language, which is English in my case. The Windows locale is set to German (Switzerland) which is in line with the way Power Bi displays the Dates in the short video above. I tried it with my windows locale set to English (US) and it behaved identically, meaning the tooltip showed false, also for a newly created visual.

**Comment by dm-p** [comment]
Thanks for confirming the details and for your reproduction steps. I can also reproduce locally now. 

It looks like the "0001" is being coerced to a number type when the Power BI tooltip handler is evaluating whether we should auto-format it, and this is then getting further evaluated as 'False' (specifically as text, not a boolean `false`).

I'll add it to the list of fixes for 1.7.

**Comment by dm-p** [comment]
I should have added that, in the meantime, this can be worked around by either:

* Switching off the tooltip handler in the Settings pane (which will fall back to Vega's inbuilt one rather than Power BI)
* Using a report page tooltip instead of the regular Power BI tooltip

**Comment by dm-p** [comment]
This has been merged to be main and available in [the alpha channel](https://github.com/deneb-viz/deneb/releases/tag/alpha) if you want to test/verify ahead of the release of 1.7. [Read more about alpha builds and the process here](https://deneb-viz.github.io/community/early-access).

**Comment by dm-p** [comment]
Hi @remsidave - did you try the 1.7 alpha build to confirm this is fixed for you? Is there anything else that needs to be done here?

**Comment by remsidave** [comment]
Hi @dm-p just tested the 1.7 alpha build and it works as expected in the minimal example and also in our company report. Thanks for fixing

**Comment by remsidave** [comment]
Hi @dm-p  just tested the 1.7 alpha build and it works as expected in the minimal example and also in our company report. Thanks for fixing

**Comment by remsidave** [comment]
Just saw https://github.com/deneb-viz/deneb/issues/483 and hence closing this one again.
