### ISSUE TITLE
Inconsistency in "Density" Transformation Results in Vega-Lite Across Different Editors

### ISSUE THREAD

**Issue by CSalcedoDataBI** [deneb-viz/deneb#451]
Hello Daniel,

While reviewing the "density" transformations in Vega-Lite, I have noticed significant discrepancies in the results obtained between two editing platforms: the Vega-Lite web editor and the Deneb editor. Both use the same Vega-Lite specification for the example of the distribution of body mass of penguins. Below, I provide the specification used:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "title": "Distribution of Body Mass of Penguins",
  "width": 400,
  "height": 80,
  "data": {"url": "data/penguins.json"},
  "mark": "area",
  "transform": [
    {"filter": "datum.Species =='Adelie'"},
    {"density": "Body Mass (g)", "groupby": ["Species"], "extent": [2500, 6500]}
  ],
  "encoding": {
    "x": {"field": "value", "type": "quantitative", "title": "Body Mass (g)"},
    "y": {"field": "density", "type": "quantitative", "stack": "zero"},
    "row": {"field": "Species"}
  }
}
```
[Open in Vega Editor](https://vega.github.io/editor/#/gist/3715e288181e1afabafac34a6c1e96f7/Test.json)

Despite using the same specification, the 'density' values differ notably. For example, for a body mass value of 2500 g, the web editor reports a density value of approximately 0.000010403897535974718, while Deneb shows a significantly lower value of approximately 4.3332416334270935e-7.

I have attached images of both results for your review. This variability affects the consistency and interpretation of analyses performed with different tools. I would greatly appreciate if you could help me understand the cause of these differences.
![Deneb Editor](https://github.com/deneb-viz/deneb/assets/73630372/18027f6b-da8e-47b8-98af-f9bb1a3b02a3)
![Online Editor](https://github.com/deneb-viz/deneb/assets/73630372/8e39acd1-25a8-41b9-b3cd-d7114e2994af)

Thank you for your attention to this matter.

Best regards,
---

**Comment by dm-p** [comment]
Hi @CSalcedoDataBI,

You will need to use an index column to guarantee uniqueness for each individual row from the dataset, and ensure that Power BI does not pre-aggregate the dataset before it hits Deneb. Without it, you will not match the granularity of the original dataset. Here's the corresponding page on this from the sample workbook:

![image](https://github.com/deneb-viz/deneb/assets/10572054/09ee6df3-2fed-4ee7-a634-cf0b385f8249)

If you add an index column, this will work as you expect, e.g.:

![image](https://github.com/deneb-viz/deneb/assets/10572054/9fbe28b9-5f27-49bc-9269-b2f745764696)

[I also wrote a blog post some years ago](https://coacervo.co/violin-plot-sampling) that explains the behavior of Power BI here and why you need to consider this for visuals that need to generate statistics over more granular data. This may help provide further clarity on why you need to do this with your visuals and how it will differ from how Vega and Vega-Lite work in this regard.

**Comment by CSalcedoDataBI** [comment]
Thank you very much for the clarification.
