### ISSUE TITLE
v1.7: PDF export not working

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#477]
From #476 by @code4578:

> Thanks for the amazing work which is much cooler and easier.
>
> I am also facing the same issue. I am unable to export to pdf from Power BI Service. The pdf is just blank.
>
> Thank you for your support

@code4578, thanks again for reaching out and reporting the issue. Can you please provide the following details so that I can investigate:

* .pbix containing the affected visual. Ideally, this should be a minimal reproducible example with public data so that I can find the root cause as soon as possible. All development and support I do on Deneb is done in my free time and for free, so a direct reproducible issue helps me to dedicate my time to fixing and getting this deployed to users faster rather than finding.

* [This section on the support page](https://deneb-viz.github.io/support#how-to-get-your-question-answered-fast) is also useful for reporting bugs and can help expedite this.

* If you cannot provide a reproducible example that can be shared publicly, you are welcome to send me the .pbix privately, and I can sign an NDA if required.

**Comment by dm-p** [comment]
I am now on 1.7, have published a report containing comments in my JSON and can successfully generate a PDF, so I'm confident that this issue is resolved.  @code4578: can you please confirm for your end?

**Comment by code4578** [comment]
Now I can confirm that the "Export to PDF" option is working with JSON comments on PowerBI service (with 1.7). Now that we have the comments feature, it is easier to work with colleagues, giving them ideas, on what these fields/specs are for. Thanks so much for looking into this @dm-p
