### ISSUE TITLE
⚠️ Visuals Appear Blurry in Power BI Service

### ISSUE THREAD

**Issue by remsidave** [deneb-viz/deneb#489]
Hello @dm-p 

We have a complex vega lite visual using concats and layers and aggregations and plotting up to 20k points as scatter plot with line overlays. This used to be rendered nicely in SVG mode but with the switch to deneb 1.7.0.0 in Power Bi Service (and only there) it now looks like it is rendered in Canvas mode (text is blurry and in general the appearance is not as sharp as it used to be). I tested this by switching another simpler plot to Canvas mode and in power Bi service the visual appearance (resolution, sharpness) is now identical to the complex plot that is set to SVG mode. 
Is it possible that the render mode is switched in the background?

If that doesn't ring a bell I can try to create a sharable version of the pbix file.

**Comment by dm-p** [comment]
This is a known issue with Chromium and affects Chrome and Edge browsers. It affects all custom visuals. I have reported to MS a few weeks ago and they are working on a fix.

**Comment by remsidave** [comment]
thanks for the swift response. Does it make sense to leave this one open or shall I close it as it already addressed?

**Comment by dm-p** [comment]
Normally I'd suggest closing, as there's nothing we can do from our end, but we'll leave it open for visibility - in case anyone else comes across the problem and wishes to report it. I'll close when we get confirmation from MS that it's fixed.

**Comment by dm-p** [comment]
@remsidave - it seems to be looking OK for me now, but it would be good to confirm from your end if there's still an issue?

**Comment by remsidave** [comment]
@dm-p it's hard to judge. I think they look less blurry, but still not as sharp as native Power Bi visuals if I compare text. 

Here's a x axis from Deneb off the Web Service
![image](https://github.com/user-attachments/assets/99723bd5-9d27-4f3f-8e46-320e80339856)

comparing to a Power Bi table header on the same report with the same zoom setting. Much sharper.
![image](https://github.com/user-attachments/assets/33fc1acc-4fd8-4ed1-9855-764bf194802c)

I know this is not for [html content](https://www.html-content.com/) but you mentioned that the underlying issue is affecting all custom visuals and text in an input field in html content still looks very blurry. From the same report on the same zoom settings
![image](https://github.com/user-attachments/assets/13cdf4ef-03e5-4030-b775-134249056cc4)

we use Edge, currently on Version 128.0.2739.67

In any case I think this is not a critical issue at all and want to thank you for your efforts here. Without Deneb, Power Bi would be missing its most important visual. Just wanted to let you know :)

**Comment by dm-p** [comment]
Thanks, both, for your input 🙏 And it's sad that it's still happening. We were given an ETA of 'about two weeks' several weeks ago, so I will follow up with MS when I return from leave in a few days

**Comment by beewishart** [comment]
Hello @dm-p , I'm not sure if you logged with MS yet but just wanted to let you know more info that I checked the same visual across 3 browsers - Edge vs Chrome vs Firefox and interestingly only Firefox displays clearly.  So matches your comment above on previous issue with Chromium seems still the case.  Unfortunately, our application users need either Edge or Chrome so hoping you hear soon.  Thanks again Bee

![Deneb visual - CHROME - blurry](https://github.com/user-attachments/assets/54846e66-656b-4e95-81a3-ad6b410e2d4a)
![Deneb visual - EDGE - blurry](https://github.com/user-attachments/assets/d68303be-2dc7-4c3a-b1e1-0f2c483cd9cc)
![Deneb visual - FIREFOX - clear](https://github.com/user-attachments/assets/9d71621a-642a-44ae-8c7d-bb168394640f)

**Comment by PBI-David** [comment]
Also seeing this in the HTML Content (Lite) visual. Please let us know if you get a response from Microsoft.

**Comment by dm-p** [comment]
The email has been sent to MS for a follow-up, but I'm still awaiting a reply as to what's happening here in terms of them resolving the problem.

**Comment by dm-p** [comment]
Update from MS: This is to be fixed by the Chromium development team. They are investigating, but there is currently no ETA on this.

I'll keep this issue open here to track interested folks in what I find out, but that's all I can offer at this time.

**Comment by beewishart** [comment]
Thank you so much for the update @dm-p  ,and understand dependency is on MS

**Comment by PBI-David** [comment]
We've raised a separate ticket at work too. Perhaps a ticket from a customer with 100k employees might get the wheels turning 🤞

**Comment by PBI-David** [comment]
Issue can be tracked here: https://issues.chromium.org/issues/359279545

**Comment by dm-p** [comment]
Chrome canary has a flag allowing developers to test a potential fix for this issue. I tested Deneb using this flag, and it looks crisp at all canvas zoom levels I tried. Let's hope it gets rolled out soon! 🤞

**Comment by dm-p** [comment]
The latest production Chrome and Edge builds are out and visuals are showing correctly for me 🎉🎉🎉

![image](https://github.com/user-attachments/assets/b067037c-5306-4493-a612-88bfff93f007)

**Comment by remsidave** [comment]
Same for me, with Edge 131.0.2903.51 deneb looks nice and crisp again

**Comment by dm-p** [comment]
Awesome! I'll close this as resolved, but keep it pinned for a bit, as there will likely be a long tail of folks needing to upgrade browsers, and it will help with self-service
