### ISSUE TITLE
Power BI Report Server May 2024 - Problem to render custom visual Deneb

### ISSUE THREAD

**Issue by LilaR-Land** [deneb-viz/deneb#493]
I am experiencing the same problem that was mentioned in  [https://github.com/deneb-viz/deneb/issues/488](url)

I have completed all the steps:
1. upgraded the Power BI Desktop to 2.129.2203.0 64-bit (May 2024)
2. downloaded  Alpha version Deneb (ALPHAdeneb7E15AEF80B9E4D4F8E12924291ECE89A.1.7.1.20240801.1b5595d)
3. Load into your workbook and created simple bar chart

but I am still encountering the same error. Screenshots of the errors and the versions of the software used are attached.
This is while, with Power BI Report Server (1.18.8683.7488(September 2023) ), I could easily develop and publish any type of chart with Deneb.

![chrome](https://github.com/user-attachments/assets/d9bb57ac-214a-434d-aa03-b3ca0ef37d89)
![DenebInPowerBiDesktop](https://github.com/user-attachments/assets/2122490b-5932-4d73-8a3c-94562f367be2)
![Version_PBIRS](https://github.com/user-attachments/assets/754737b5-b0fe-469c-901c-e92b81a4a3a8)
![error](https://github.com/user-attachments/assets/7d0009ce-615f-429a-b23f-21d187625c96)

**Comment by dm-p** [comment]
Hi @LilaR-Land - did you download [the alpha from the linked issue](https://github.com/deneb-viz/deneb/issues/488#issuecomment-2282919430) or the current published alpha from the main repo? Unfortunately I haven't updated this yet so would be good to confirm which one you're using before I check further.

**Comment by LilaR-Land** [comment]
This link contains a file .pbiviz.json
It is not possible to import in Power BI desktop.

![Pbiviz](https://github.com/user-attachments/assets/0f4283bd-ec25-4ac4-bd0e-7a289b26b2a1)

**Comment by dm-p** [comment]
As per instructions on comment, rename extension from .zip to .pbiviz (GH doesn't allow attaching of non standard files to issues). You will then be able to impoet manually.

**Comment by LilaR-Land** [comment]
Thank you very much.
Before this, I got the alpha version from another source . After getting your link, I made a mistake by unzipping the file and then renaming it.

But with your help I succeeded.  Thank's 🙏🙏

**Comment by dm-p** [comment]
Thanks for confirming! I've been busy with work, but I plan to release this and some other changes as an official AppSource update (1.7.2) very soon. I'll close this ticket when the submission has been made (and then it'll take up to 3 weeks for MS to verify and deploy).

**Comment by dm-p** [comment]
1.7.2 has been submitted to AppSource, so this should be live in your reports in a few weeks. For now, the standalone edition is available in the typical manner. [This blog post](https://deneb-viz.github.io/blog/1-7-2-submission) provides links to the change log and info if you'd like to use the standalone version in the meantime.
