### ISSUE TITLE
Feature request: multiple data sources

### ISSUE THREAD

**Issue by vfridkin** [deneb-viz/deneb#505]
Vega can accept multiple data sources, which comes in very useful when importing fact and multiple dimension tables.  With a single data source I have to pre-join the dimension data and with large datasets (up to 10K) it means wider tables that I believe affects performance.  

A use case is showing a description on hover.  If only a few data points need descriptions, it is a waste repeating these descriptions in a column thousands of times.

**Comment by dm-p** [comment]
Unfortunately, this isn't possible in the Power BI visual. Power BI only supports a single query. Of course, you can declare a static dataset inline, but it is not possible to obtain this from another place within Power BI. Microsoft does not intend to support multiple queries or data sources for a visual, so you will need to work around this as you currently do.

The only possible workaround in Power BI is to use the standalone/uncertified version to define or load a dataset from an external source (provided that the external source allows communications from a sandboxed iframe).

**Comment by PBI-David** [comment]
@dm-p  could the solution proposed here not support this requirement?

https://github.com/deneb-viz/deneb/issues/194

> We might be better off allowing a property that allows geojson to be supplied via conditional formatting and parsing this as a separate named dataset, which would keep the load off the editor.

**Comment by dm-p** [comment]
Yes something like this is in scope for v2 but
