### ISSUE TITLE
Vega-lite: Clicking on a datapoint in a scrollable visual jumps back up to the top

### ISSUE THREAD

**Issue by triCNguyen5** [deneb-viz/deneb#508]
I have a horizontal bar chart, that has the "step" property specified for the height, see screenshot below. Simple cross filtering is enabled because I use Vega-lite. When I click on a bar position anywhere on the visual, it jumps back up to the top. Screenshot below describes it.

![image](https://github.com/user-attachments/assets/b7e9deab-e057-4716-8859-fbd3743abb62)

**Comment by dm-p** [comment]
This would be facilitated by delivering #410

**Comment by triCNguyen5** [comment]
Hey, thanks for the quick reply. I am looking forward to the enhancement.

**Comment by dm-p** [comment]
We'll track this in the resolution of #410, so I'll close this to reduce the number of duplicates on the backlog. Feel free to keep an eye on #410 for news and opportunities to test and validate when v2 gets closer to that point (not for a while yet, but it's moving along steadily)
