### ISSUE TITLE
Cross-Filtering Support

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#6]
During prototyping, we identified issues with implementing selection/cross-highlighting generically, as it depends on Power BI's selection API and some compliance from the developer of a specification. At a high-level, we should achieve the following as part of this work:

- [ ] Prototype suitable approaches and support for:
    - [ ] `single` view
    - [ ] `layer` view
    - [ ] `concat` view
    - [ ] `facet` view
    - [ ] `repeat` view
- [ ] Migrate out of legacy `selectionHandlerService` into `selection` API
- [ ] Abstract as much as possible into signal handlers
- [ ] Scope and document commitment from developer to implement, as well as gotchas and requirements.

**Comment by dm-p** [comment]
From doing more research into this, we will struggle to do this in a complete manner at this time. I am still up-skilling in some of the deeper aspects of Vega's ecosystem, so this represents my best understanding of the current state of the landscape.

We need to be able to set selections within a Vega/Vega-Lite visualisation in order to support clearing of selections through external events, e.g. clearing selections via the Power BI selection manager, other visuals having selections applied (which may also trigger the former if our visual doesn't contain any eligible data from this selection), as well as being able to restore bookmarks containing selections. 

Ideally, we will need an API for reading/writing selections in a more scalable manner. This is currently outstanding (roadmap item - vega/roadmap#9; feature request - vega/vega-lite#1830). Additionally, reading [how selection IDs work inside Power BI visuals](https://docs.microsoft.com/en-us/power-bi/developer/visuals/selection-api?WT.mc_id=DP-MVP-5003712) may help to clarify the current challenges for anyone who is interested.

----

What we have had some success within Power BI in terms of prototyping is the following approach. This is similar to how we might code a dedicated custom visual, with some caveats due to the flexibility of what we are trying to offer:

- Expose the option to enable selection in the Advanced Editor UI.
- However we set the the property to `OFF` by default - meaning that the creator has to opt in for any visuals and therefore accepts the limitations if they wish to proceed.
 - Add an `EventListenerHandler` to the view that listens for `click` events on the view (rather than a `SignalListenerHandler` against a selection defined in a spec, or a `DataListenerHandler` against a particular selection store).
 - If the click event exposes a `datum`, attempt to:
     - Attempt to obtain the row identity from it. If the row correlates directly against the source data (i.e. is "pure") then this is fine and we can trust the next part of the process is okay.
     - If there is no identity (e.g. datum has been transformed and only contains 'necessary' fields) then we can attempt to resolve an identity from it like we do for report page tooltips and context menus. The difference here is that we can consolidate multiple data points for selection (e.g. if grouped by facet).
- If the `ctrl` key is held when doing this, we can add the derived identities to the existing list rather than replacing it, which will allow users to multi-select marks.
- Sensibly work out if a multi-selection should toggle an existing data point, e.g. it's clicked again while `ctrl` is held.
- If anything other than a mark is selected, or we cannot identity a datum, or a click results in all data being identified (and therefore no real need to specifically select) then, we can clear the current selection in the correct way and signal this to other visuals that may have cross-highlights applied.
- We will use the selection manager's selection callback to set a `___status___` field against each row in the dataset with one of the following values:
    - `off`: the data row is currently not selected and should be displayed however the creator deems necessary to communicate this to their readers
    - `standard`: the data row has no selection applied to it and should be displayed normally
    - `selected`: the data row is explicitly included in the visual's selection and as such, this can be used to add extra visual indicators that may not be desirable if  `__status__ == 'standard'` 

This has the following advantages:

- None of this affects context menu functionality - that can work and is being implemented separately.
- For simple specifications, the act of clicking a mark that binds to a datum will work as expected.
- The creator will only need to apply cosmetic changes to a mark to indicate selection status, e.g.:
   ```json
    ...
    "opacity": {
        "condition": {
            "test": {
                "field": "__status__",
                "equal": "off"
              },
            "value": 0.3
        },
        "value": 1
    }
    ...
    ```
- This will support restoring of an active selection from a bookmark.
- Should we get timely access to a suitable API, the above solution could remain as a "let Deneb manage for me" approach to getting started with selections. We could develop deeper integration with such an API for creators that want to go all-out on interactivity and allow options for either from the creator side of things.
- Creators can still use the inbuilt functionality (e.g. Vega-Lite `params` within a visual, albeit without any outbound functionality (like now).

...and the following disadvantages:

 - This will only work for marks, so we cannot wire-up other elements like legends.
 - Any marks representing an aggregate value cannot easily contain the `__status__` field, so we may not be able to apply encodings to these kinds of marks based on that field. 
     - We may need to accept for now that these kinds of higher level marks can be used for selecting marks that represent lower-level data points, but we will not be able to style them accordingly (although I am still looking into this point).
     - We have to assume that any higher-level aggregates will always contain all underlying data points (i.e. not filtered). Grouping would be okay, e.g. facets, providing there is no filtering (again, still looking into this as it relates to the above point).

---

I'm confident that while the above does not leverage the flexibility on offer inside Vega and Vega-Lite, it does provide some middle-ground that should appease some creators. The alternative is that we delay any further work on this until a Vega selections API is available (noting that this feature request is currently > 4 years old, as this requires a lot of thought from the Vega end also).

However, I'm keen to get any further thoughts on this from any users before I spend any more time on it. It's certainly easier to say we don't/can't support this, but if the above can work for some then it might be worth the effort. There's also bound to be additional perspectives that others can bring that I may not currently be seeing.

**Comment by kolky001** [comment]
"However, I'm keen to get any further thoughts on this from any users before I spend any more time on it. It's certainly easier to say we don't/can't support this, but if the above can work for some then it might be worth the effort. "

There may be a tonne of people that would go to great lengths to have cross-highlighting available from Deneb to other visuals. 

For me, in thinking about my use cases, I would guess that less than a quarter of the visuals I would want to build in Deneb, I would be seeking cross-highlighting from Deneb. Without having given it a go, the above solution seems a little too involved for me. If I really needed cross-filtering I might be inclined toward another solution at this stage.

**Comment by dm-p** [comment]
I've made a couple of revisions to the above approach, notably:

* The dataset field is now named `__selected__` rather than `__status__`
* The potential values of this field are either `off`, `neutral` or `on`

From a visual effects perspective, we can resolve dataset rows (and their selection IDs) from these marks and pass them to Power BI's selection manager. While we can't easily aggregate the `__selected__` statuses, we could introduce a pattern such as aggregating the sum of data points with a particular value and create marks that bind suitable attributes to these aggregates, e.g.:

```
...
  "transform": [
    {
      "calculate": "datum.__selected__ == 'off' ? 0 : datum['$ Sales']",
      "as": "Selected_Sales"
    }
  ],
...
```

![image](https://user-images.githubusercontent.com/10572054/132447588-dd6db5b6-7c09-459c-ac42-f631793bf2e1.png)

In this case, the final 'row' is selected, so the sum of these values creates a fully solid bar in its total. 

As only the last row of each column is selected, the column's total bar is partially displayed against another, less opaque mark. The sum of selected values from each column produces a 'partial highlight' based on the first mark's value. The the second, less opaque mark behind it will show the sum of all values, so if a row or column is fully 'selected' the darker mark obscures it.
