### ISSUE TITLE
Add Dataset Information to Visual Editor

### ISSUE THREAD

**Issue by dm-p** [deneb-viz/deneb#7]
It would be useful to provide at least some high-level information about the visual dataset in the visual editor, such as:

- Number of rows
- Measure/column metadata
- Limited preview of rows

**Comment by kolky001** [comment]
If possible, like the Vega editor, to see original vs. transformed data in data viewer

**Comment by dm-p** [comment]
Intention is to expose all data streams (like the editor does)

**Comment by dm-p** [comment]
Initial functionality introduced in 1.3's first alpha build. If there are any further issues, please create a new issue with the prefix `[1.3 Alpha Testing]` and I'll flag for follow-up.
